name: sse_channel2
description: StreamChannel wrappers for Server Sent Events.
version: 0.0.4
repository: https://www.github.com/benco8186/sse_channel

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  http: ^1.2.1
  pool: ^1.5.1
  sse: ^4.1.5
  stream_channel: ^2.1.2
  uuid: ^4.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
